@startjson

skinparam BoxPadding 10
skinparam actorStyle awesome
skinparam LegendBorderThickness 1
skinparam backgroundColor transparent

#highlight  "投標結束日前, IPO"
#highlight  "投標結束日前, IPO" / "股票代號"
#highlight  "投標結束日前, IPO" / "公司名稱"


#highlight  "投標結束日前, PER" / "股票代號"
#highlight  "投標結束日前, PER" / "公司名稱"

#highlight  "投標結束日前, 競拍時程" / "股票代號"
#highlight  "投標結束日前, 競拍時程" / "公司名稱"

#highlight  "開標日當日後, 開標資訊" / "股票代號"
#highlight  "開標日當日後, 開標資訊" / "公司名稱"

{
  "投標結束日前, IPO": {
    "申請日期": "20240730",
    "股票代號": "4749",
    "公司名稱": "新應材",
    "董事長": "詹文雄",
    "申請時股本": "821747650",
    "上櫃審議委員會審議日期": "20241105",
    "櫃買董事會通過上櫃日期": "20241129",
    "櫃買同意上櫃契約日期或證期局核准上櫃契約日期": "20241204",
    "股票上櫃買賣日期": "",
    "主辦承銷商": "兆豐",
    "承銷價": "",
    "備註": ""
  },

  "投標結束日前, PER": {
    "股票代號": 4747,
    "公司名稱": "強生",
    "收盤價": "",
    "殖利率(%)": 2.11,
    "股利年度": 112.0,
    "本益比": 39.01,
    "股價淨值比": 1.89,
    "財報年/季": "",
    "每股股利(註)": 1.49839697
  },
  "投標結束日前, 競拍時程": {
    "序號": "4",
    "開標日期": "2025/01/03",
    "公司名稱": "新應材",
    "股票代號": "4749",
    "發行市場": "櫃檯買賣",
    "發行性質": "初上櫃",
    "競拍方式": "美國標",
    "投標開始日": "2024/12/27",
    "投標結束日": "2024/12/31",
    "競拍數量(張)": 7,
    "最低投標價格(元)": 406,
    "最低每標單投標數量(張)": 410.26,
    "最高投(得)標數量(張)": 1,
    "保證金成數(%)": 925,
    "每一投標單投標處理費(元)": 50,
    "撥券日期(上市、上櫃日期)": 400,
    "主辦券商": "2025/01/17",
    "得標總金額(元)": "兆豐",
    "得標手續費率(%)": 0,
    "取消競價拍賣(流標或取消)": 0
  },
  "開標日當日後, 開標資訊": {
    "公司名稱": "新應材",
    "股票代號": "4749",
    "得標總金額(元)": "兆豐",
    "得標手續費率(%)": 0,
    "總合格件": 5,
    "合格投標數量(張)": 0,
    "最低得標價格(元)": 0,
    "最高得標價格(元)": 0,
    "得標加權平均價格(元)": 0,
    "承銷價格(元)": 0
  }
}
@endjson
