@startjson

skinparam BoxPadding 10
skinparam actorStyle awesome
skinparam LegendBorderThickness 1
skinparam backgroundColor transparent

#highlight  "投標結束日前, IPO"

#highlight  "投標結束日前, IPO" / "股票代號"
#highlight  "投標結束日前, IPO" / "公司名稱"

#highlight  "投標結束日前, PER" / "股票代號"
#highlight  "投標結束日前, PER" / "公司名稱"

#highlight  "投標結束日前, 競拍時程" / "股票代號"
#highlight  "投標結束日前, 競拍時程" / "公司名稱"

#highlight  "開標日當日後, 開標資訊" / "股票代號"
#highlight  "開標日當日後, 開標資訊" / "公司名稱"


{
  "投標結束日前, IPO":     {
  "申請日期": "2024/04/29",
  "股票代號": "8272",
  "公司名稱": "全景軟體",
  "董事長": "楊瑞明",
  "申請時股本": 171977550,
  "上櫃審議委員會審議日期": "2024/06/28",
  "櫃買董事會通過上櫃日期": "2024/07/19",
  "櫃買同意上櫃契約日期或證期局核准上櫃契約日期": "2024/07/23",
  "股票上櫃買賣日期": "2024/10/23",
  "主辦承銷商": "富邦",
  "承銷價": 59,
  "備註": ""
    },

  "投標結束日前, PER":     {
        "股票代號": "8272",
        "公司名稱": "全景軟體",
        "收盤價": null,
        "殖利率(%)": 2.54,
        "股利年度": 112.0,
        "本益比": 23.44,
        "股價淨值比": 4.96,
        "財報年/季": null,
        "每股股利(註)": 2.87
    },
  "投標結束日前, 競拍時程":     {
        "序號": 51,
        "開標日期": "2024/10/08",
        "公司名稱": "全景軟體",
        "股票代號": "8272",
        "發行市場": "櫃檯買賣",
        "發行性質": "初上櫃",
        "競拍方式": "美國標",
        "投標開始日": "2024/10/02",
        "投標結束日": "2024/10/04",
        "競拍數量(張)": 1224,
        "最低投標價格(元)": 50.86,
        "最低每標單投標數量(張)": 1,
        "最高投(得)標數量(張)": 159,
        "保證金成數(%)": 50,
        "每一投標單投標處理費(元)": 400,
        "撥券日期(上市、上櫃日期)": "2024/10/23",
        "主辦券商": "富邦",
        "取消競價拍賣(流標或取消)": null
    },
  "開標日當日後, 開標資訊": {
    "公司名稱": "全景軟體",
    "股票代號": "8272",
    "得標總金額(元)": 105285380,
    "得標手續費率(%)": 5,
    "總合格件": 1244,
    "合格投標數量(張)": 9176,
    "最低得標價格(元)": 80.85,
    "最高得標價格(元)": 168.8,
    "得標加權平均價格(元)": 86.02,
    "承銷價格(元)": 59.0
  }
}
@endjson
